# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjZe8BI9_L0fSwyVkNZtoKR_5izqgNJf
"""

!pip  install  cryptography

"""***HELLO***"""